#!/usr/bin/env python3

'''
Please run this file as ./loose_equality_checks_searcher.py from within its parent directory.
Otherwise, the paths will not be generated/printed correctly.
'''

from typing import List

import os


INTERESTING_FILES_EXTENSIONS: List[str] = [".ts", ".tsx", ".js"]
FILES_EXCLUSION_LIST: List[str] = [os.path.basename(__file__)]
DIR_EXCLUSION_LIST: List[str] = ["node_modules", "static"]
OUTPUT_FILE: str = "LOOSE_EQUALITY_CHECKS.md"
PATTERNS: List[str] = [" == ", " != "]
HEADER: str = "# List of loose equality checks"


def main() -> None:
    lines: List[str] = []

    for dir, _, files in os.walk(os.getcwd()):
        if os.path.basename(dir) in DIR_EXCLUSION_LIST or any(d in dir for d in DIR_EXCLUSION_LIST):
            continue

        for f in filter(lambda candidate: any(filter(lambda ext: isinstance(ext, str) and candidate.endswith(ext), INTERESTING_FILES_EXTENSIONS)), files):
            if f not in FILES_EXCLUSION_LIST:
                lines += __look_for_loose_equality_checks(os.path.join(dir, f))

    with open(OUTPUT_FILE, "w") as f:
        f.write(HEADER + "\n\n")

        for line in lines:
            f.write(line + "\n\n")

        f.write("**This file is autogenerated. Please do not edit it manually.**\n")
        f.flush()


def __look_for_loose_equality_checks(path: str) -> List[str]:
    to_add: List[str] = []
    path_to_print: str = __get_relative_path(absolute_path=path)
    prefix: str = "* File [{}]({}) - line ".format(path_to_print, path_to_print)
    lines: List[str] = []

    with open(path, "r") as f:
        lines = f.readlines()

    for i in range(len(lines)):
        line_number = i + 1

        if any(pattern in lines[i] for pattern in PATTERNS):
            to_add.append(prefix + "{}: `{}`".format(line_number, lines[i].strip().replace("`", "'")))

    return to_add


def __get_relative_path(absolute_path: str) -> str:
    tokens: List[str] = absolute_path.split(os.path.sep)
    vw_top_dir: str = os.path.basename(os.getcwd())

    while tokens[0] != vw_top_dir:
        tokens = tokens[1:]

        if len(tokens) < 2:
            raise ValueError("Malformed path: {}".format(absolute_path))

    tokens = tokens[1:]

    return os.path.join(*tokens)


if __name__ == "__main__":
    main()
