#!/usr/bin/env python3

from re import match

import os


INTERESTING_EXTENSIONS = [".py", ".cjs", ".jsx", ".ts", ".tsx", ".html", ".css", ".json", ".md", ".txt", ".sh", ".gitignore"]
DIRECTORIES_TO_IGNORE = ["node_modules", ".git"]
PATTERNS = [r"[ \t]+$", r"[ \t]+\n$"]
PROJECT_DIR: str = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
LOG_FILE: str = os.path.abspath(os.path.join(os.path.dirname(__file__), "WHITE_SPACES.md"))
FILES_EXCLUSION_LIST: list[str] = [os.path.basename(__file__), os.path.basename(LOG_FILE)]


def main() -> None:
    lines: list[str] = []

    for d, _, files in os.walk(PROJECT_DIR):
        if any(ignored in d for ignored in DIRECTORIES_TO_IGNORE):
            continue
        else:
            lines += __scan_files(d, files)

    with open(LOG_FILE, "w") as f:
        f.write("# List of redundant white spaces\n\n")

        for line in lines:
            f.write(line + "\n\n")

        f.write("**This file is autogenerated. Please do not edit it manually.**\n")
        f.flush()


def __scan_files(d: str, files: list[str]) -> list[str]:
    lines: list[str] = []

    for f in files:
        if os.path.join(d, f) not in FILES_EXCLUSION_LIST and any(f.endswith(ext) for ext in INTERESTING_EXTENSIONS):
            lines += __scan_file(d, f)

    return lines


def __scan_file(d: str, f: str) -> list[str]:
    to_return: list[str] = []
    lines: list[str] = open(os.path.join(d, f)).readlines()

    for i in range(len(lines)):
        if any(match(pattern, lines[i]) for pattern in PATTERNS) or __multiple_spaces_within_line(lines[i].strip()):
            to_return.append(os.path.join(d, f) + ": line " + str(i + 1) + ".")

    return to_return


def __multiple_spaces_within_line(line: str) -> bool:
    line = line.replace(r"\"\s+\"", "").replace(r"'\s+'", "")

    for i in range(len(line) - 1):
        if line[i] == " " and line[i + 1] == " " and not line[i + 1:].strip().startswith(("//", "/*", "#")):
            return True
    return False


if __name__ == "__main__":
    main()
